version: '3.7'

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    stdin_open: true
    tty: true
    command: npm start
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true